#!/usr/bin/python3

import sys

## comment 
## comment2 

def tonm(s)
    try:	
        ans += int(line)
    except:
        ans += float(line)
ans=0
for line in sys.stdin:
    line = line.rstrip()
    ans = tonum(line)

print(ans)
